#!/bin/bash -xeu

# shellcheck disabled=SC1091
source cf-deployment-concourse-tasks/shared-functions

BUILD_DIR=${PWD}

function main() {
	cd concourse-tasks/cloudsql-setup/terraform/

	terraform init
	terraform apply -var "project=${GCP_PROJECT}" --auto-approve --state="env-repo/${BBL_STATE_DIR}"
}

trap commit_bbl_state_dir "${BUILD_DIR}" 'Update bbl state dir' EXIT

main
