#!/bin/bash -xeu

# shellcheck disabled=SC1091
source cf-deployment-concourse-tasks/shared-functions

function main() {
    setup_bosh_env_vars

    cd concourse-tasks/cloudsql-setup/terraform/
    terraform init
    terraform apply --auto-approve --state="env-repo/${BBL_STATE_DIR}" cloudsql.tf
}

trap close_bbl_ssh_connection_and_commit_vars_store EXIT

main
