#!/bin/bash -xeu

# shellcheck disabled=SC1091

BUILD_DIR=${PWD}

function set_git_config() {
  if [ -z "${GIT_COMMIT_USERNAME}" ]; then
    GIT_COMMIT_USERNAME="CI Bot"
  fi

  if [ -z "${GIT_COMMIT_EMAIL}" ]; then
    GIT_COMMIT_EMAIL="cf-release-integration@pivotal.io"
  fi

  git config user.name "${GIT_COMMIT_USERNAME}"
  git config user.email "${GIT_COMMIT_EMAIL}"
}


function commit_bbl_state_dir {
  local root_dir
  root_dir="${BUILD_DIR}"
  commit_message="Update state"

  pushd "${root_dir}/env-repo/${BBL_STATE_DIR}"
    if [[ -n $(git status --porcelain) ]]; then
      set_git_config
      git add --all .
      git commit -m "${commit_message}"
    fi
  popd

  pushd "${root_dir}"
    shopt -s dotglob
    cp -R env-repo/* updated-env-repo/
  popd
}

function main() {
	cd concourse-tasks/terraform-init-and-apply/${TERRAFORM_DIR}/

	terraform init
	terraform apply -var "project=${GCP_PROJECT}" --auto-approve --state="${BUILD_DIR}/env-repo/${BBL_STATE_DIR}/terraform/concourse-tasks-terraform-state.tf"
}

trap commit_bbl_state_dir EXIT

main
